-- ============================
-- PHOTOS TABLE (Photography Gallery)
-- ============================

CREATE TABLE IF NOT EXISTS public.photos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  description text,
  image_url text NOT NULL,
  category text DEFAULT 'general',
  order_index int DEFAULT 0,
  is_published boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

-- ============================
-- RLS POLICIES
-- ============================

ALTER TABLE public.photos ENABLE ROW LEVEL SECURITY;

-- Public can read published photos
CREATE POLICY "public read published photos"
ON public.photos FOR SELECT
USING (is_published = true);

-- Admin can manage all photos
CREATE POLICY "admin manage photos"
ON public.photos FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
);

-- ============================
-- STORAGE BUCKET
-- ============================

-- Create bucket for photos if not exists
INSERT INTO storage.buckets (id, name, public)
VALUES ('photos', 'photos', true)
ON CONFLICT (id) DO NOTHING;

-- Admin can upload photos
CREATE POLICY "admin upload photos"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'photos'
  AND EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
);

-- Admin can delete photos
CREATE POLICY "admin delete photos"
ON storage.objects FOR DELETE
USING (
  bucket_id = 'photos'
  AND EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  )
);

-- Public can read photos
CREATE POLICY "public read photos"
ON storage.objects FOR SELECT
USING (bucket_id = 'photos');

-- ============================
-- SAMPLE DATA (optional)
-- ============================

-- Uncomment to add sample data
-- INSERT INTO public.photos (title, description, image_url, category, order_index, is_published)
-- VALUES 
--   ('Sunset at Beach', 'Beautiful sunset photography', 'https://example.com/photo1.jpg', 'landscape', 1, true),
--   ('City Lights', 'Urban night photography', 'https://example.com/photo2.jpg', 'urban', 2, true),
--   ('Portrait', 'Professional portrait session', 'https://example.com/photo3.jpg', 'portrait', 3, true);
